export const SET_EDITOR_REF = Symbol('i4004/SET_EDITOR_REF');
export const START_COMPILATION = Symbol('i4004/START_COMPILATION');
export const FINISH_COMPILATION = Symbol('i4004/FINISH_COMPILATION');
export const UPDATE_EMULATOR_STATE = Symbol('i4004/UPDATE_EMULATOR_STATE');
export const BUILD_AND_RUN = Symbol('i4004/BUILD_AND_RUN');
export const SELECT_MEMORY_BANK = Symbol('i4004/SELECT_MEMORY_BANK');
