export const SET_EDITOR_REF = Symbol('i4004/SET_EDITOR_REF');
export const START_COMPILATION = Symbol('i4004/START_COMPILATION');
export const FINISH_COMPILATION = Symbol('i4004/FINISH_COMPILATION');
export const SET_CONFIGURATION = Symbol('i4004/SET_CONFIGURATION');
export const START_CONFIGURATION = Symbol('i4004/START_CONFIGURATION');
export const FINISH_CONFIGURATION = Symbol('i4004/FINISH_CONFIGURATION');
